//
//  HomeViewController.swift
//  MediQuoTest
//
//  Created by Filipe on 03/03/2020.
//  Copyright (c) 2020 Filipe Mota. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: class {
    func displaySomething(viewModel: Home.Something.ViewModel)
}

class HomeViewController: UIViewController, HomeDisplayLogic, APIClientDependency {
    var api: APIClient!
    var router: Router!
    private(set) var route: Route!
    var interactor: HomeBusinessLogic?
  
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
    }

    private func setup() {
      let viewController = self
      let interactor = HomeInteractor()
      let presenter = HomePresenter()
      viewController.interactor = interactor
      interactor.presenter = presenter
      presenter.viewController = viewController
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        doSomething()
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
    func doSomething() {
        let request = Home.Something.Request()
        interactor?.doSomething(request: request)
    }
  
    func displaySomething(viewModel: Home.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}


extension HomeViewController: Routable {
    static func instantiate() -> UIViewController & Routable {
        guard let result = UIStoryboard(name: "Home", bundle: nil).instantiateInitialViewController() as? HomeViewController else {
            fatalError()
        }
        return result
    }

    func setup(_ route: Route) {
        switch route {
        case .home:
            self.route = route
        }
    }
}
