# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'MediQuoTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'PKHUD'

  # Pods for MediQuoTest

  target 'MediQuoTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
